name: PaperDrugs
version: 1.0.0
main: com.tieman114.PaperDrugs
description: A plugin adding drugs dor our private mc server
author: TieMan114
website: N/A
api-version: '1.20'
commands:
  getWTEgg:
    description: Adds 1 Wandering Trader Spawn Egg to the players inventory
  getDrugs:
    description: Adds 16 of everything that has to do with drugs