name: PaperDrugs
version: 0.1
main: com.tieman114.paperdrugs.PaperDrugs
description: A plugin that adds drugs and other things to Minecraft.
author: Tieman114
website: N/A
api-version: '1.20'
commands: 

permissions:
  paperdrugs.admin:
    description: Allows the player to use all PaperDrugs commands.
    default: op
  paperdrugs.use:
    description: Allows the player to use all PaperDrugs items.
    default: true
